// Even or Odd: O(1)
// Are you Here: O(n^2)
// Doubler: O(n)
// Naive Search: O(n)
// Creating Pairs: O(n^2)
// Computing fibonaccis: O(n)
// An Efficient Search: O(log(n))
// Random Element: O(n)
// Is it prime: O(n)
