// Count Sheep: O(n)
// Array Double: O(n)
// Reverse String: O(n)
// Triangular Number: O(n)
// Split: O(n)
// ConvertToBinary: O(n)
// Factorial: O(n)
// Fibonacci: O(n)
// Anagram: O(n^2)
// Animal Hierarchy: O(n)
// Organization Chart: O(n)
